# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f671a5a93184b47a9e8318b529b2dd42"
name = "my-new-app"
handle = "my-new-app-1218"
application_url = "https://pins-however-price-preference.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pins-however-price-preference.trycloudflare.com/auth/callback",
  "https://pins-however-price-preference.trycloudflare.com/auth/shopify/callback",
  "https://pins-however-price-preference.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
